### ISSUE TITLE
[Client] 컴포넌트 구조 설계

### ISSUE THREAD

**Issue by BrisLun** [GraduationMovie/GraduationMovie#8]
리액트 & 노드로 하기로 함!

- [ ] 컴포넌트 구조 설계

**Comment by broccolism** [comment]
@BrisLun 피그마에서 썼던 Play 폰트도 적용해보고 제대로 되는지 확인해줘! 안되면 다른거 골라야하니까

**Comment by BrisLun** [comment]
> @BrisLun 피그마에서 썼던 Play 폰트도 적용해보고 제대로 되는지 확인해줘! 안되면 다른거 골라야하니까

OK!
